# Config file for automatic testing at travis-ci.org

sudo: required
dist: trusty
# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
group: deprecated-2017Q4
language: python

addons:
    addons:
        firefox: latest

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

matrix:
    fast_finish: true
    include:
        - env: TOXENV=py35
          python: 3.5

        - env: TOXENV=py36
          python: 3.6

        - env: TOXENV=py37
          python: 3.7

        - env: TOXENV=pypy3
          python: pypy3

before_install:
    #
    # install Chromium Browser + Selenium WebDriver for it:
    - sudo apt-get update
    - sudo apt-get install chromium-browser chromium-chromedriver
    #
    # install Selenium Firefox WebDriver 'geckodriver':
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz -O geckodriver.tar.gz
    - mkdir $PWD/geckodriver
    - tar -xvf geckodriver.tar.gz -C $PWD/geckodriver
    - ls -la $PWD/geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - geckodriver --version

install:
    # install only the needed package to run tox
    # tox will install all needed packages
    - travis_retry pip install tox coveralls python-creole docutils

script:
    - ./setup.py tox

after_success:
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
    - coveralls
